### ISSUE TITLE
VeryFastTree: out of memory error

### ISSUE THREAD

**Issue by emiliomastriani** [citiususc/veryfasttree#10]
Hello,
I would like to use VeryFastTree v. 3.1.0 on Ubuntu 21.10 (Aliens Aurora R13, 62Gb Ram, 12th Gen. intel i9-12900KF x 24) to build the phylogenetic tree from the aligned data file (nucleotide, 5.4Gb). 

Of course, I followed the standard steps to configure/install the package (cmake . ; make ; make install)

I tried to run it with many options, but I got the same kind of errors.  
On the terminal:

emilio@Alienware:/mnt/NTFS/test_new/clustering-based$ time ~/Downloads/veryfasttree-master/VeryFastTree otus.fasta_aln > fast_tree.tree
Command: /home/emilio/Downloads/veryfasttree-master/VeryFastTree otus.fasta_aln
VeryFastTree Version 3.1.0 (OpenMP, AVX2, DEBUG) with SSE3
Alignment: otus.fasta_aln
Amino acid distances: BLOSUM45 Joins: balanced Support: SH-like 1000
Search: Normal +NNI +SPR (2 rounds range 10) +ML-NNI opt-each=1
TopHits: 1.00*sqrtN close=default refresh=0.80
ML Model: Jones-Taylor-Thorton, CAT approximation with 20 rate categories
Killed5.01 seconds: Identified unique sequences   

real    2m58.015s
user    2m18.278s
sys     0m15.013s

On the log file (/var/log/syslog):
Jan  5 11:43:48 Alienware kernel: [1126344.427488] Out of memory: Killed process 3734287 (VeryFastTree) total-vm:64621716kB, anon-rss:63708292kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:126500kB oom_score_adj:0

For the extended log file, please check the attachment.

How can I solve the problem?

I also tried to use Fasttree2, but I gained the same error.

Thank you for your help

Emilio Mastriani, PhD

[log.txt](https://github.com/citiususc/veryfasttree/files/7811959/log.txt)

**Comment by cesarpomar** [comment]
VFT is a reimplementation of fasttree 2, a code that fails in fasttree 2 will also fail in VFT because, except for optimizations, the algorithm is the same.

Looking at the log, it looks like you have run out of memory, the quickest option is to increase your swap partition.

Thank you for using the tool
