### ISSUE TITLE
double free or corruption (!prev) error

### ISSUE THREAD

**Issue by Jadelrea** [citiususc/veryfasttree#12]
Hello,

Thank you for this nice tool.

I am working on a large alignment of ~29,000 samplesG and ~1.4MB length. When I run varyfasttree-3.2.1 (using an initial tree)  on a machine with 500Gb RAM and 12 threads, it crushes at the ML stage. That's why I tried to run it on a cluster using 600G RAM and 20 threads (I'm trying to avoid monopolizing the whole server but I could use up to 2T RAM). However, there I could only get the admin to install version 3.2.0 for me, and I got the following error: 

>Command: VeryFastTree -threads 20 -mlnni 4 -gtr -nt -intree run_alignment_no_resis_no_clus-2737768.nwk run_alignment_no_resis_no_clus.fas
VeryFastTree Version 3.2.0 (OpenMP, SSE) with SSE3 using threads(20) level 1 deterministic
Alignment: run_alignment_no_resis_no_clus.fas
Nucleotide distances: Jukes-Cantor Joins: balanced Support: SH-like 1000
Start at tree from run_alignment_no_resis_no_clus-2737768.nwk +NNI +SPR (2 rounds range 10)
ML Model: Generalized Time-Reversible, CAT approximation with 20 rate categories
    211.74 seconds: Read alignment
    211.74 seconds: Hashed the names
    219.10 seconds: Identified unique sequences
Refining topology: 59 rounds ME-NNIs, 2 rounds ME-SPRs, 4 rounds ML-NNIs
double free or corruption (!prev)
Aborted (core dumped)>

I guess I would like to know whether this error has to do with version, so I will try to get the server people to install a different one, or there is something else I could be missing. Anyway, any suggestion would be very welcome. Thank you!

**Comment by cesarpomar** [comment]
Thanks for using our tool, we're glad you find it helpful. The issue you are experiencing is related to version 3.2.0 [(Issue11),](https://github.com/citiususc/veryfasttree/issues/11) which has been resolved in version 3.2.1. We recommend that you use version 3.2.1 as it resolves the "core dumped" error.

Compiling Veryfasttree is easy and you don't need admin access to do it. You can download version 3.2.1 on the cluster and use "cmake . && make" to obtain a fully optimized binary for the cluster. Keep in mind that if you need to use 500GB of RAM, it means you have a very large dataset and you may want to check out the "-threads-level 2" or other optimization options. You can check the 3.2.1 readme or use -expert for help.

We're also working on version 3.3 which is even faster, especially for large datasets like yours. It's not quite done yet, but we invite you to give it a try.

**Comment by Jadelrea** [comment]
Thank you for your suggestions César.

I finally run my dataset on version 3.3. This time, it could complete it. However, the software log suggested to run veryfasttree with the -double-precision argument, which I did not do.

Also, at the final step, "ML split tests", it reported the following:
>Total time: 412400.68 seconds Unique: 29729/29801 Bad splits: 29726/29726 Worst delta-LogLk 104.879
TreeCompleted

Could you give me some insight on what this ratio of bad splits means?  Is it indicative of weakly supported branches? Thanks!

**Comment by cesarpomar** [comment]
I assume you mean: "WARNING! This alignment consists of closely-related and very-long sequences. Consider using VeryFastTree with -double-precision.", which means that the tool detected that for such closely-related sequences, a more valid result will be obtained if the calculations are performed with more precision numeric operations. It is a recommendation, it does not imply that the result in your case will not be correct.

Veryfasttree is a highly optimized version of [FastTree-2](http://www.microbesonline.org/fasttree/), for questions about "the genetic part", its documentation may be useful. [In this part ](http://www.microbesonline.org/fasttree/constrained.html):
`
"Bad" splits are locations in the tree where a nearest-neighbor interchange would reduce the length of the tree -- if you run  FastTree with constraints, then there will be more of these than normal. (Note that the maximum likelihood phase of FastTree may correctly introduce splits that lengthen the tree but increase the likelihood.)
`

I hope I have answered your questions, do not hesitate if you have any other questions,

Best,
César

**Comment by cesarpomar** [comment]
I'm closing the issue as it has already been resolved and there has been no new activity.
