### ISSUE TITLE
Gaps/indels, missing and/or masked characters in terminal positions

### ISSUE THREAD

**Issue by JGLAHE** [citiususc/veryfasttree#15]
How are sequence gaps/masked regions treated in Veryfasttree?

Veryfasttree threw an error that it was expecting a larger number of sequences because I had some sequences starting with gaps (coded as `-` characters). Recoding to `?` got around this this problem, although it still gives a warning about non-nucleotide characters being present, so I'm curious about how these (and `NNN`/`X` masking) is being interpreted?

Cheers

**Comment by cesarpomar** [comment]
Changing "-" to "?" should not affect anything; all non-blank unknown characters are treated as gaps. If you can provide me with an input that reproduces the error, I can check if it's a bug. Don't worry about the warnings, they should be just indicating that "?" is being treated as gaps. 

Cheers

**Comment by JGLAHE** [comment]
Cheers, I cannot reproduce this issue in the current release
