### ISSUE TITLE
VeryFastTree support values are -1

### ISSUE THREAD

**Issue by lukaszsobala** [citiususc/veryfasttree#16]
Hello,

I noticed a difference between the results from FastTree and VeryFastTree. In case of many trees, the support values reported by VFT are -1 while they are between 0 and 1 for FastTree (2.1.11). What may be the cause of this?

**Comment by cesarpomar** [comment]
Hi,

It could be due to a bug that I may not have detected. Could you provide me with a set of input sequences where I can replicate the error and show me at which point you've noticed it?

Best regards

**Comment by lukaszsobala** [comment]
Thanks for fixing. Most of the trees I made were like this - sorry, I didn't have time to send them yet.

**Comment by lukaszsobala** [comment]
@cesarpomar is my intuition that previously `VeryFastTree` was labelling any bad splits with "-1" correct?

**Comment by SAMtoBAM** [comment]
Any update on this?
I have -1 for all support values

**Comment by lukaszsobala** [comment]
@SAMtoBAM try using the latest version (also available through conda/mamba), it's been fixed.
