### ISSUE TITLE
constrained topology and core dumps

### ISSUE THREAD

**Issue by sihellem** [citiususc/veryfasttree#17]
Hi!

I am having troubles in using VeryFastTree in constrained mode, with:
```VeryFastTree -gtr -nt aln.fasta -constraints tree_constraints.txt > tree.tree```

I structured "tree_constraints.txt" as found on the original documentation of FastTree (http://www.microbesonline.org/fasttree/constrained.html). Hence using 0s, 1s, and hyphens.

However, VeryFastTree returns:
```
Command: VeryFastTree -gtr -nt aln.fasta -constraints tree_constraints.txt
VeryFastTree Version 4.0.2 (OpenMP, AVX512) with SSE3 using threads(40) level 3 deterministic
Alignment: aln.fasta
Nucleotide distances: Jukes-Cantor Joins: balanced Support: SH-like 1000
Search: Normal +NNI +SPR (2 rounds range 10) +ML-NNI opt-each=1
TopHits: 1.00*sqrtN close=default refresh=0.80
ML Model: Generalized Time-Reversible, CAT approximation with 20 rate categories
Constraints: tree_constraints.txt Weight: 100.000
     13.96 seconds: Read alignment
     15.77 seconds: Identified unique sequences
No sequence in phylip line: sample_1  -11
```

It would be great to add an example files on the GitHub repository for future reference.

Bests,

**Comment by sihellem** [comment]
Quite interestingly, if I generate the constraint file through the perl utility of FastTree, with:
```
wget http://www.microbesonline.org/fasttree/TreeToConstraints.pl
perl TreeToConstraints.pl < constraints.nex > constraints.txt
```

VeryFastTree directly coredumps without any informative error:
```
Identified 3 constraints for 2529 sequences
/var/spool/slurmd/job28425592/slurm_script : ligne 88 : 2282968 Instruction non permise (core dumped)VeryFastTree -threads ${SLURM_CPUS_PER_TASK} -gtr -nt aln.fasta -constraints constraints.txt > ree.tree
```

**Comment by cesarpomar** [comment]
Hi,

To investigate this, I need you to provide me with more information. Have you compiled the tool on the same machine where you are running it? Can you share aln.fasta and tree_constraints.txt for us to attempt to replicate the issue?

Best regards

**Comment by cesarpomar** [comment]
Since "Instruction non permise" can only occur when executing an instruction that is not compatible with the hardware, it is most likely that an incompatible binary was used. The error occurred in the constraints because that was the point where the compiler generated the first incompatible instruction. Nevertheless, the constraints have been reviewed, and the error could not be reproduced.
