### ISSUE TITLE
[feature] Python bindings

### ISSUE THREAD

**Issue by tomdstanton** [citiususc/veryfasttree#21]
Hi guys,

Thank you so much for this fantastic resource! 😄 
Would you consider adding Python bindings in the future to allow Pythonistas such as myself to interface with VFT directly?

Thanks in advance,
Tom

**Comment by cesarpomar** [comment]
I like it

The easiest way would be a Python binding that calls the VeryFastTree binary as a subprocess, something like the GitPython library.

The longest way would be to compile the C++ code when installed with pip as part of the library.

What is your opinion as a Pythonista?

Thanks for your proposal

**Comment by cesarpomar** [comment]
VeryFastTree Python bindings ready and released in PyPi

https://pypi.org/project/veryfasttree

**Comment by tomdstanton** [comment]
Fantastic! Thanks for all your work! 😄
