### ISSUE TITLE
Failure at Neighbor Joining

### ISSUE THREAD

**Issue by Cyoung02** [citiususc/veryfasttree#3]
Running Very FastTree fails when I run it on the following dataset:
[full.true.aln.zip](https://github.com/citiususc/veryfasttree/files/5242376/full.true.aln.zip)

here's how i ran it
```
cat ../full.true.aln | VeryFastTree -gamma -nt -gtr -out veryfast.tre -log veryfastlog2.log -verbose 999
```

and here's the error message:
```
3966.46 seconds: ML Lengths 1 of 2320 splits
VeryFastTree: /home/colin/Desktop/NiemaLab/comparisons/veryfasttree/src/NeighbourJoining.tcc:1029: double veryfasttree::NeighbourJoining<Precision, Operations>::pairLogLk(veryfasttree::NeighbourJoining<Precision, Operations>::Profile&, veryfasttree::NeighbourJoining<Precision, Operations>::Profile&, double, double*) [with Precision = float; Operations = veryfasttree::SSE128Operations]: Assertion `lkAB > 0' failed.
Aborted (core dumped)
```

Thanks

**Comment by cesarpomar** [comment]
Hi, sorry by the delay. I will look for the problem.

**Comment by cesarpomar** [comment]
Asset errors are legacy FastTree checks. Your dataset is too large for debugging tests (more than 2 hours and no errors), I need a smaller dataset.

**Comment by cesarpomar** [comment]
I've tested with VeryFastTree 4.0 and no errors were found. I'm closing the issue, but you can reopen it if needed.
