### ISSUE TITLE
VeryFastTree changes the input tree topology, just like FastTree

### ISSUE THREAD

**Issue by balabanmetin** [citiususc/veryfasttree#5]
There's this known issue in FastTree where -intree does not preserve the input tree topology (see the title "Why does -intree -nome -mllen change the tree topology in rare cases?" at [fasttree website](http://www.microbesonline.org/fasttree/).

This issue seems to persist in VeryFastTree as well.

**Comment by cesarpomar** [comment]
Hi,
VeryFastTree  is a reimplementation of Fasttree, the original source code has been optimized and parallelized but the algorithm is the same. If you have any suggestions to improve the algorithm, I will make the necessary changes to implement it.
Thanks,
César
