### ISSUE TITLE
VeryFastTree NJ branch lengths do not match FastTree, and they are probably wrong

### ISSUE THREAD

**Issue by balabanmetin** [citiususc/veryfasttree#7]
Output trees for the following two commands are dramatically different. 

`FastTreeMP  -nt -nosupport  -nome -noml -log true_me.fasttree.log -intree astral.lpp.nwk < ref.fa > true_me.fasttree`
`VeryFastTree  -nt -nosupport  -nome -noml -log true_vme.fasttree.log -intree astral.lpp.nwk < ref.fa > true_vme.fasttree`

Input files mentioned are uploaded here.
https://drive.google.com/drive/folders/1JznPSkoB8pJB-mSZd2HBDf1xjkkeoDtw?usp=sharing

**Comment by cesarpomar** [comment]
Hi, I'll check the behavior of the dataset in the next few days.

**Comment by roblanf** [comment]
@balabanmetin I have a hypothesis here (I'm nothing to do with either piece of software, but I've been using FastTree a lot...), any chance you can upload your output files as well as the input files?

Rob

**Comment by balabanmetin** [comment]
@roblanf hi! I uploaded the output files in the same directory

**Comment by roblanf** [comment]
Thanks. I note that both trees have negative branch lengths, so it might be worth looking into that (some tips are on the fasttree 2 site for this). Notably, the VeryFastTree tree has a lot of very long negative (and positive) branchlenghts that are absent in the FastTree tree.

But also, the two trees have different taxa in them, so there's obviously more here than meets the (or my) eye...

```
> t1

Phylogenetic tree with 10198 tips and 10196 internal nodes.

Tip labels:
	G001873755, G001567355, G001567305, G000993565, G000991265, G001771775, ...

Unrooted; includes branch lengths.
> t2

Phylogenetic tree with 10575 tips and 10405 internal nodes.

Tip labels:
	G001873755, G001567355, G001567305, G000993565, G000991265, G001771775, ...

Unrooted; includes branch lengths.
```

**Comment by cesarpomar** [comment]
Hi,

I executed with FastTree and VeryFastTree:
  -nt -nosupport -nome -noml -intree astral.lpp.nwk ref.fa

and always read 10575 tips. In your logs I can see that FastTree read 10198 tips, it is very strange, check if you used the same input file and tell me.

**Comment by balabanmetin** [comment]
I realized I uploaded the wrong output file for FastTree. I updated the output files, now they are the correct ones.  as @roblanf pointed out there are some very short negative branches in VeryFastTree output (search for -0.6).

**Comment by cesarpomar** [comment]
I will close the issue because it is related to VeryFastTree 3.0.1, which was deprecated in favour of the 4.0 major release.
