### ISSUE TITLE
Bioconda

### ISSUE THREAD

**Issue by rfarouni** [citiususc/veryfasttree#9]
Hi,

I wasn't able to find the package on Bioconda. Do you have any plans of adding a build recipe there?

Best,

**Comment by cesarpomar** [comment]
I know, you can use this file while we carry out the process to publish the tool in bioconda.

**Comment by cesarpomar** [comment]
In process: [pull request](https://github.com/bioconda/bioconda-recipes/pull/31065)

I will close the issue as soon as it is available.
